### ISSUE TITLE
In-text citation links do not scroll to citations

### ISSUE THREAD

**Issue by absempere** [recogito/recogito-client#134]
When looking at styling in [this document](https://recogito-staging.covecollective.org/en/annotate/bdb710d1-b165-42d9-a068-1178c5d082d7/153e6e85-7b06-497d-b074-ada65cd986a1) on Staging, I noticed that the in-text links aren't working as expected on the page. If I click one of the in-text citations, the page does not scroll to the corresponding footnote. However, if I [open the link in a new tab](https://recogito-staging.covecollective.org/en/annotate/bdb710d1-b165-42d9-a068-1178c5d082d7/153e6e85-7b06-497d-b074-ada65cd986a1#note41back), the document opens to the correct citation. The same happens with the ["Back" link](https://recogito-staging.covecollective.org/en/annotate/bdb710d1-b165-42d9-a068-1178c5d082d7/153e6e85-7b06-497d-b074-ada65cd986a1#note41) at the end of each citation -- the page does not scroll, but in a new tab, the page opens to the correct anchor.

**Comment by SteveMarvin** [comment]
inline links work fine for me

**Comment by SteveMarvin** [comment]
not sure what's going on...for some reason this issue cannot be moved to the accepted column, and the pipeline will not allow change manually.

**Comment by SteveMarvin** [comment]
ah, ok thanks
