### ISSUE TITLE
Project admin without org permissions can't send invites

### ISSUE THREAD

**Issue by ajolipa** [recogito/recogito-client#15]
Currently it seems as though sending an invite is failing at the stage of selecting a row from the `project_groups` table, even though it looks to me from looking at the policies like someone with a project admin role should be able to select from that table, at least rows relevant to the project they're an admin of.

Note that currently this error is not being handled well/at all -- you will get a "user invited" alert despite it not working. That should also be fixed.

**Comment by rsimon** [comment]
This seems to be resolved now. Closing the issue. However, there are some more cases we should handle properly. I'll create an issue on the main issue tracker.

**Comment by rsimon** [comment]
See here: https://github.com/performant-software/vico/issues/109
