### ISSUE TITLE
Annotations in the active layer are shown underlined

### ISSUE THREAD

**Issue by jsmueller7** [recogito/recogito-client#219]
(tested with beta.5)

I have just created a work order and included documents of several supported types. In an annotation session with several testers, the annotations of the active layer were only underlined in black, not highlighted in color. In this document, I included the (empty) base layer.
Tested on Chrome and Firefox.

**Comment by rsimon** [comment]
I think this is fixed now. At least I haven't seen it happen after @lwjameson's recent backend layer fixes.

**Comment by SteveMarvin** [comment]
This is approved, but for some reason I can't move the issue to that column.
