### ISSUE TITLE
Filtering options aren't dynamic

### ISSUE THREAD

**Issue by jsmueller7** [recogito/recogito-client#266]
When I open a document in the base layer, I can filter by “Created by” and “Tags”. In my opinion, the suggestions for “Created by” and “Tags” should depend dynamically on the selected layers. The current status is that I can filter on a tag or a person even if they do not appear in the selected layer.

**Comment by rsimon** [comment]
Agreed! I'm preparing a PR with some smaller annotation view fixes, which will include this change.
