### ISSUE TITLE
Header bar doesen't break well on small screens

### ISSUE THREAD

**Issue by jsmueller7** [recogito/recogito-client#281]
First I tested this on my smartphone. But this seems also to be a problem on tablets and you can even reproduce this in a regular browser window: If you move the window together, a scroll bar appears at the bottom. At the top right, the toolbar protrudes.

![Bildschirmfoto vom 2024-10-09 14-00-11](https://github.com/user-attachments/assets/7bf0b60d-fd06-4e3b-9737-47fb0f1224b3)

**Comment by SteveMarvin** [comment]
This issue is approved, but I cannot move it. @rsimon @lwjameson
