### ISSUE TITLE
'Loading' state for text (and image) annotation

### ISSUE THREAD

**Issue by rsimon** [recogito/recogito-client#3]
It looks like creating annotations before the annotations from the DB have loaded causes problems. An easy fix would be to introduce a 'loading' state for the whole page, preventing pointer activity on the text/image canvas. But, additionally: need to investigate what happens. Most likely, the initial load _replaces_ all annotations in the state store, whereas it should add to.

**Comment by rsimon** [comment]
This is now available in the `development` branch. The annotation UI is masked, with a load spinner, until document and annotations have fully loaded. (https://github.com/recogito/recogito-client/pull/105)

**Comment by SteveMarvin** [comment]
This issue is approved, but won't seem to move to that pipeline.
