### ISSUE TITLE
'Make this annotation public' feature for private annotation

### ISSUE THREAD

**Issue by rsimon** [recogito/recogito-client#5]
The feature is currently only 50% implemented.
- The menu option exists
- Selecting the menu option will update the `is_private` flag in the DB
- Annotation privacy status changes immediately for me

However, the status is not reflected in realtime for the other connected users. (They would have to reload the page.) A bit of extra plumbing is needed in the Annotorious Supabase plugin to handle the incoming change message:
- CDC will report an update on an annotation the client doesn't have
- We _may_ want to confirm that the update includes `is_private === false`, for sanity
- We then need to __fetch target and bodies with an extra request__, because those aren't included in the CDC update, and we can't render the annotation without them.

**Comment by jamiefolsom** [comment]
Done!
