### ISSUE TITLE
Add "view ignored" functionality to invites list

### ISSUE THREAD

**Issue by ajolipa** [recogito/recogito-client#8]
Presumably ignoring an invitation shouldn't make it impossible ever to see it again!

**Comment by rsimon** [comment]
I was thinking about working this into the new notifications popover component I showed in our call yesterday. I found this screenshot on Dribble:
https://dribbble.com/shots/20392799-Notifications-Tetrisly-Design-System

And I think we can do the same thing, i.e. have a tab bar at the top with two options: "New", "Archive", and then Archive would show the ignored ones.

**Comment by rsimon** [comment]
Closing this in favor of: https://github.com/performant-software/vico/issues/128
