### ISSUE TITLE
Password reset and Invite User emails behavior on click is incorrect

### ISSUE THREAD

**Issue by lwjameson** [recogito/recogito-client#98]
Both take you directly into the app without allowing you to set a password.

**Comment by rsimon** [comment]
Hm, this seems to work for me. When logged out, I can go to /en/forgot-password and enter my email. The email contains a link to /reset-password, which allows me to choose a password. (Even when logged in, it looks like the flow is working correctly & can just choose a new password.)

I tried this on Chrome/Mac.

**Comment by rsimon** [comment]
BTW: the invite link is set from the Supabase config, right? I assume this should point to `{base}/reset-password`.

**Comment by SteveMarvin** [comment]
Not getting invite emails. Cannot test

**Comment by SteveMarvin** [comment]
When I click on the link to reset my password, it just logs me straight back in via the existing cookie.

**Comment by SteveMarvin** [comment]
For some reason I can't move this to Rejected/Returned.

**Comment by SteveMarvin** [comment]
This issue is accepted, but I can't seem to move it to the corresponding pipeline
